name: Update WakaTime Readme Stats

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write  # ← this gives the action permission to push changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: athul/waka-readme@v0.2.3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          LANG_COUNT: 5
          SHOW_TOTAL: true
          TARGET_BRANCH: main
          TARGET_PATH: README.md
