name: Update WakaTime Readme Stats

on:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: wakatime/wakatime-readme@v1
        with:
          api_key: ${{ secrets.WAKATIME_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
