name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-waka:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: athul/waka-readme@v0.2.3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
