name: Update WakaTime Readme Stats

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          LANG_COUNT: 5
          SHOW_TOTAL: true
          TARGET_BRANCH: main          # Change to 'master' if your default branch is master
          TARGET_PATH: README.md       # Change if your README path is different
