name: Update WakaTime Readme Stats

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-waka:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: nordcloud/waka-readme-action@v1.1.0
        with:
          wakatime_api_key: ${{ secrets.WAKATIME_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
